name: Daily newsletter workflow

on:
  schedule:
    - cron: '0 11 18 2 *'
    - cron: '0 11 30 4,6,9,11 *'
    - cron: '0 11 31 1,3,5,7,8,10,12 *'
    - cron: '0 11 29 2 *'
  workflow_dispatch:

jobs:
  Query-And-Notification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-dotenv
          python -m pip install pandas
          python -m pip install Jinja2
      - name: Send newsletter to friends
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
        run: |
          python main.py