name: Daily newsletter workflow

on:
  schedule:
    - cron: '0 11 30 9,11 *'
    - cron: '0 12 30 4,6 *'
    - cron: '0 11 31 1,3,10,12 *'
    - cron: '0 12 31 5,7,8 *'
    - cron: '0 11 29 2 *'
    - cron: '0 11 28 2 *'
  workflow_dispatch:

jobs:
  Query-And-Notification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-dotenv
          python -m pip install pandas
          python -m pip install Jinja2
          python -m pip install pillow
          python -m pip install requests
          python -m pip install pillow-heif
      - name: Send newsletter to friends
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
          RECIPIENT_SPARK: ${{ secrets.RECIPIENT_SPARK }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
          BACKGROUND_URL: ${{ secrets.BACKGROUND_URL }}
        run: |
          python main.py

          git config --global user.name ${{ secrets.GIT_USERNAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git add *
          git commit -m "update log"
          git push